### PR TITLE
Make fallback class loader configurable

### PR DESCRIPTION
**Pull request by juliarn**
This pr changes the following:

- Adds the possibility to set an own class loader for loading the sources, leads to better compatibility 
- Updates srgutils to 5.1

### CODE REVIEW

**Comment by LexManos** [comment]
1) Don't combine feature requests
2) Setting the classloader is not the intended mechanic for controlling the classpath. The intention is to specify the libraries as libraries. The classloader is just a fallback intended to get the base java classes.
3) What is the point of knowing if things are running? The run() method is blocking. So as long as that method is sill executing then running will be true.

**Comment by juliarn** [comment]
Alright, I removed the isRunning method. I still think it would be useful to be able to control the fallback class loader.

**Comment by LexManos** [comment]
Why?

**Comment by juliarn** [comment]
I do not need all the libraries of Minecraft for remapping it. I currently have the problem, that some library classes which are changed via Mixin, are loaded too early because of the remapper. To solve this, I could either provide all libraries, although I do not need them, or I could just supply another fallback class loader which handles this. The second one would be the way simpler solution, although it might not be intented like this.

**Comment by LexManos** [comment]
Mixins should not be running when FART is running. What are you using this for? In what project?
What do you mean loaded 'too early'? FART is a static tool to remap a binary. It has to have access to the entire classpath so that it can calculate the inheritance correctly and propagate any mappings that are needed. Mixin should have nothing to do with this process as they are dynamic. Yes I know there are projects to apply them statically, but in that case it's just more libraries you need.

**Comment by juliarn** [comment]
I use it to remap mods before they are loaded. I do not add the Minecraft authlib as a library to the remapper, for example (because it isn't really needed for remapping). But because Minecraft uses the authlib, the remapper tries to load its classes to check if there is any information needed for remapping. Because it uses the current class loader, the authlib classes are now loaded. After the remap is complete, the game starts and a mixin of a mod tries to manipulate the authlib classes. This fails because the authlib is already loaded in the same class loader. Well I guess the best fix would be to just add the authlib to the libraries, but collecting all Minecraft libraries is not that easy when the game itself is already running.

**Comment by LexManos** [comment]
Why are you remapping mods during loading?

**Comment by juliarn** [comment]
Because the mappings of the mods do not match the mappings of the client itself. The mods are just put in a folder by the user, so there isn't really another way, because the mods should be available immediately.

**Comment by LexManos** [comment]
I understand the mappings of A are not the mappings of B. That's the entire function of this project. To convert something from A to B.
What I am trying, and apparently failing, to do is get all of the context out of you so that I can fully understand your use case. 
And there is another option, you can have the mods reobf to SRG names like Forge supports natively during build. 

Anyways, feel free to move this to discord/#github-discussion to try and justify your use case better. 'Just shove the classloader at it' is the antithesis of what we've designed the system to do. If you have anything that is not base java, then it should be included as a library.

**Comment by juliarn** [comment]
I get that my case is quite special and adding everything as a library would be impractical for me, I guess I will stick to my fork. I just thought that being able to control how and where the classes are loaded from can be quite important, even if it's just the fallback.

**Pull request closed without merging**
